language: node_js
node_js:
- "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - "npm run build"
  # sonar not on pull requests for the moment
  - "npm run sonar -Dsonar.host.url=https://sonarcloud.io"
