language: node_js
node_js:
    - "node"
cache:
    directories:
        - "node_modules"
install:
    - npm install
script:
    - npm run build
    - PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo sonar.projectVersion=$PACKAGE_VERSION >> sonar-project.properties
    - npm run sonar -- -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
